/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default'];
    IwyBreadcrumbs: typeof import('./components/IwyBreadcrumbs.vue')['default'];
    IwyNavigation: typeof import('./components/IwyNavigation.vue')['default'];
  }
}
